# Generated by Django 5.0.6 on 2024-06-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_session_mahshulot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='mahshulot_id',
            field=models.ManyToManyField(related_name='sessions', to='my_app.mahshulot'),
        ),
    ]
