# Generated by Django 5.0.6 on 2024-06-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_alter_session_mahshulot_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frist_name_your', models.CharField(max_length=255)),
                ('last_name_your', models.CharField(max_length=255)),
                ('email_your', models.EmailField(max_length=254)),
                ('phone_your', models.CharField(max_length=13)),
                ('affiliation_your', models.CharField(max_length=150)),
                ('country_your', models.CharField(max_length=255)),
                ('frist_name_autor', models.CharField(max_length=255)),
                ('last_name_autor', models.CharField(max_length=255)),
                ('email_autor', models.EmailField(max_length=254)),
                ('phone_autor', models.CharField(max_length=13)),
                ('affiliation_autor', models.CharField(max_length=150)),
                ('country_autor', models.CharField(max_length=255)),
                ('title_paper', models.CharField(max_length=255)),
                ('section_paper', models.CharField(max_length=255)),
                ('keyword_paper', models.IntegerField()),
                ('file_paper', models.FileField(upload_to='')),
            ],
        ),
    ]
